avinash201199/Free-courses-with-Certificates

README.md

I have checked the commits. 
Please review the changes and merge it labelling `hacktoberfest-accepted`.

Issue #1 : Added free android development course

---

README.md

I've added 3 free course for Cyber Security, Linux, and Python from Cisco Networking Academy and you'll earn certificate once you complete the course.

Add free course by Cisco NetAcad for some topics

---

README.md

Added Responsive Web Design Course

---

README.md

MySQL course added

---

README.md

Added free certificate courses from freecodecamp.org .

Updated Readme for ML and Javascript

---

CONTRIBUTING.md
README.md

Added Get Ahead with Front-end Development

---

README.md

Adding php links

---

README.md

always wanted to learn react so had bookmarked this

added a course by free code camp

---

index.html

Added a toggle button to make it responsive

---

README.md
main.js

Added Back-end and C++ free certification courses

Back-end and C++ 

---

README.md

- kaggle free machine learning certification.
- https://www.kaggle.com/learn/intro-to-machine-learning

Added Machine Learning course

---

README.md
main.js

Added a popular website for building Dapps under blockchain course

Added blockchain course

---

README.md

Was not present previously.Kindly add it .

Added Pwoer BI course for beginners

---

README.md
main.js

Add ruby content

---

README.md
main.js

@avinash201199  please assign me this issue #161

To add  Introduction to HTML5 by coursera

---

README.md

Added new learnweb.io website in the blockchain technology section.

Added new course in blockchain

---

README.md

Added free android app development course with Certification in educba

Added Educba free android app development course

---

README.md

Add solidity certificate #188 Get NFT certificate

Add solidity certificate #188 Get NFT certificate

---

README.md
src/components/data/allcourses.json

Really sorry sir,
I tried to rectify my mistake this time.
Thank you

Rectified one

---

README.md
src/components/data/allcourses.json

Added two cloud computing courses to address issue #206

Updated allcourses.json

---

README.md
src/components/data/allcourses.json

Issue addressed #205 -> https://github.com/avinash201199/Free-courses-with-Certificates/issues/205

Added course for SQL and relational Database 

---

README.md
src/components/data/allcourses.json

added fundamentals of digital marketing course by google digital garage

added digital marketing course

---

src/components/data/allcourses.json

Added course for Jenkins

---

src/components/data/allcourses.json

I add the incredible AWS Cloud Quest Game to get the free badge of cloud practitioner

Adding an AWS Course

---

README.md
src/components/data/allcourses.json

Add flask to python tools

---

README.md
src/components/data/allcourses.json

@avinash201199 added the necessary details.
Do assign the hacktoberfest label.

(Google-Cloud-training-by-qwiklabs-and-google

---

README.md

This course covers the following topics:
1. Fundamentals of Marketing on different social media
2. Facebook Marketing
3. Instagram Marketing
4. Marketing on Twitter

learnmall digital marketing course

---

README.md
src/components/data/allcourses.json

Google Analytics for Beginners shows new users how to create an account, implement tracking code, and set up data filters, to navigate the Google Analytics interface and reports, and set up dashboards and shortcuts. The course will also demonstrate how to analyze basic Audience, Acquisition, and Behavior reports, and set up goals and campaign tracking.

Google Analytics for Beginners

---

README.md
src/components/data/allcourses.json

The Courses added about is free of cost along with the Certificate.

Added Courses for Python, SQL, and for Docker

---

README.md
src/components/data/allcourses.json

Added details of Docker and Kubernetes free courses.

Added details of Docker and Kubernetes free courses

---

README.md
src/components/data/allcourses.json

This course is for data science aspirants. A very well-defined course by Kaggle for analysis of Geographical dataset analysis. Best domain to grow your skills

Geospatial analysis by Kaggle free course added

---

README.md
src/components/data/allcourses.json

Issue: #292 
This is 𝒇𝒓𝒆𝒆 𝒄𝒆𝒓𝒕𝒊𝒇𝒊𝒄𝒂𝒕𝒆 from 𝐆𝐨𝐨𝐠𝐥𝐞 Tech dev Guid by learning 𝐃𝐚𝐭𝐚 𝐒𝐭𝐫𝐮𝐜𝐭𝐮𝐫𝐞𝐬 𝐚𝐧𝐝 𝐀𝐥𝐠𝐨𝐫𝐢𝐭𝐡𝐦𝐬 with free practice material.
The course is available in four programming languages (Javascript, Java, C++ and Python)

Added free DSA certificate course

---

README.md
src/components/data/allcourses.json

Add new python courses and delete extra commas

[ADD] python courses of cisco, fix extra commas

---

package.json
src/components/AboutPage.jsx
src/components/sidemenu.jsx
src/main.jsx

Added an about page following the steps laid out in #302 
https://user-images.githubusercontent.com/27888345/196641690-faf11797-eb5a-4c7f-88a0-84e945e2e06c.mp4

#302 about page

---

README.md
src/components/data/allcourses.json

Added a new machine learning crash course from Google developers community #324 
Repo Maintainers, it would be great if you'll can add hacktoberfest label :) thankyou

Added a new machine learning crash course

---

README.md
src/components/data/allcourses.json

Hi! I am a new hacktoberfest participant, and have added the above course into the repository that I raised in issue #332. Please accept my PR. Thank you!

Adding the Kaggle Data Visualisation course

---

src/components/data/allcourses.json

Added new courses for andriod and data structure

Added new courses for andriod and data structure

---

README.md
src/components/data/allcourses.json

Added 2 courses related to Blockchain Technology, which are from Cadena and KBA. They provide fundamental knowledge related to Blockchain and practical implementations (cryptocurrency and DApp development).

Add Blocckhain Technology courses

---

README.md
src/components/data/allcourses.json

Added free PHP course from Great Learning

Added Free PHP course.

---

README.md
src/components/data/allcourses.json

New Category added.
New course portal added under that.

Added New Free Course Portal in Integration Platform Space

---

README.md
src/components/data/allcourses.json

Please, add topic "hacktoberfest-accepted" in PR.

Add Data Visualization course #369

---

README.md
src/components/data/allcourses.json

Google Cloud Pro (Italian)

---

README.md
src/components/data/allcourses.json

Data structures and Algorithms in Python (https://jovian.ai/learn/data-structures-and-algorithms-in-python), an excellent certification course for people of all skill levels. Has an in-built notebook for running your programs in the website itself, detailed documentation with video support too.

Data Structures and Algorithms in Python

---

README.md
src/components/data/allcourses.json

Added course for flutter in all courses and updated readme.

Added Flutter Course

---

README.md

This course is from Meta (Facebook)

Added free resources for becoming a front end developer

---

README.md
src/components/data/allcourses.json

Link: https://www.educative.io/courses/learn-rust-from-scratch

Added Free Rust Course with Certificate.

---

README.md
src/components/data/allcourses.json

Added the Data Structures and Algorithms course (in Python) offered by Google, which is available for free on Udacity. #Hacktoberfest2022

Added the DSA course by Google (Issue #376 )

---

README.md

Under the UI/UX section you have doubled the future learn course, and I deleted the last one.

Deleted a repeated course

---

README.md

I have added a link that would provide a free certificate for the learner and emphasized the description from the title with italics and bold text along with the ommition of the web link under the title for better consistency

Added a new link to Harvard course

---

README.md
src/components/data/allcourses.json

Added the course Data Structure and Algorithms in JavaScript

Updated of readme file and allcourses.json file 

---

README.md
src/components/data/allcourses.json

updated Readme and  allcourses.json file

Course Added 

---

package-lock.json
package.json
postcss.config.js
src/App.css
src/App.jsx
src/components/Dashboard.jsx
src/components/Outsideclick.jsx
src/components/allcourse.jsx
src/components/navbar.jsx
src/components/sidemenu.jsx
src/hooks/useDashboard.js
src/index.css
src/main.jsx
tailwind.config.js

when the user **clicks outside the dropdown will be closed** and also **added close button** for closing dropdown which is great user experience

added functionality for closing search dropdown

---

package-lock.json
package.json
postcss.config.js
src/App.css
src/App.jsx
src/components/AboutPage.jsx
src/components/Dashboard.jsx
src/components/Layout.jsx
src/components/NaviBar.jsx
src/components/Outsideclick.jsx
src/components/allcourse.jsx
src/components/featured.jsx
src/components/footer.jsx
src/components/main.jsx
src/components/navbar.jsx
src/components/sidemenu.jsx
src/hooks/useDashboard.js
src/index.css
src/main.jsx
tailwind.config.js

created a layout and the components inside the layout only changes without doing a hard refresh when we navigate to about or courses or dashboard and also added tailwind css and lucide react icons for the functionality of the dashboard.
The community put every thing to position to absolute in css I modified some of them

added routes to dashboard,about,home  and modified css

---

src/App.css
src/components/Dashboard.jsx
src/components/navbar.jsx

styled scroll bar and changed overflow of dashboard

---

README.md
src/components/data/allcourses.json

This removes a course that has a dead link:
https://www.coursera.org/learn/server-side-nodejs?ranMID=40328&ranEAID=JVFxdTr9V80&ranSiteID=JVFxdTr9V80-BhGyVRqGfwfzbqKem2Q0Aw&siteID=JVFxdTr9V80-BhGyVRqGfwfzbqKem2Q0Aw
This course doesn't seem to exist anymore.
Completed for Hacktoberfest 2023 :)

Remove Node.js Course (no longer exists and links to 404)

---

src/index.css

This pull request contains the updated code for '_Bug: "Featured Section" Content is Crossing its Set Width_'. The width is set to the correct width. The issue associated with this pull request is as follows:
Bug: "Featured Section" Content is Crossing its Set Width #417
**Current Design**
**Updated Design**

'Featured Courses' Section Bug Resolved

---

src/components/sidemenu.jsx

@avinash201199 
#423  completed Please Check out My PR If It's ok Please Thumbs up :+1:

 Fix toogleMenu in Mobile Display

---

src/App.jsx
src/components/ErrorPage.jsx
src/components/Layout.jsx
src/components/navbar.jsx
src/styles/errorpage.css

Fixes :  #426
please review my PR and If any issue occur let me know !

Added 404 error page 

---

package-lock.json
package.json
src/App.jsx
src/components/Login.jsx
src/components/Register.jsx
src/components/Requireauth.jsx
src/components/UserState.js
src/components/navbar.jsx
src/firebase.js
src/hooks/useInputField.js

user cant visit the page without authentication and you will be automatcally logged out if you close the window or the tab and you can see the user name on the nav bar this is small project so i kept my env variables directly into the code

added authentication using firebase 

---

README.md
src/components/data/allcourses.json

This PR contains the source of added "Operating system Course" : https://github.com/avinash201199/Free-courses-with-Certificates/issues/431
Close : https://github.com/avinash201199/Free-courses-with-Certificates/issues/431

[Hacktoberfest'23] : Added Operating System Course

---

src/components/Dashboard.jsx
src/components/ErrorPage.jsx
src/components/allcourse.jsx
src/components/featured.jsx
src/components/navbar.jsx
src/styles/errorpage.css
src/styles/footer.css

Fixes :#436
- I have solve this issue as well as search input css fix for small device.
After Change:
https://github.com/avinash201199/Free-courses-with-Certificates/assets/87563885/e1d7de83-c970-4f75-875a-6a0905af5f29
Please Chekout PR and Commit If find any issue otherwise thumbs up :+1:

Fix:search course redirected  errorpage

---

README.md
src/components/data/allcourses.json

This is a free projects based sql certification course provided by freecodecamp.
After completing the course they will provided a free certificate.

Add Sql Free Certification Course

---

README.md
src/components/data/allcourses.json

Add A New Course Title "Software Testing/Quality Assurance"
In this course title I add a new  course "Quality Assurance and Testing with Chai" provided by freecodecamp.
This course is completly free and provided free certificate after complete this course.

Add A New Course Title "Software Testing/Quality Assurance" 

---

README.md
src/components/data/allcourses.json

Added Courses about software testing

---

README.md
src/components/data/allcourses.json

 Added new course for git 

---

README.md
src/components/data/allcourses.json

@avinash201199 please review it.
This issue is related to #454  and should be fixed by the changes in #455.

added docker essential course

---

README.md
src/components/data/allcourses.json

I have added the Django course which was not present
@avinash201199 Thank you 🙂

Updated Django course and added links of W3Schools, Geeks for Geeks and more

---

README.md
src/components/data/allcourses.json

@avinash201199 Can you please review the contribution and label it hacktoberfest-accepted.
issue #461

added new course

---

README.md
src/components/data/allcourses.json

Add Basics of networking course in Computer networking course title.
It is a free certification course provided by Greate Learning.

Add free networking course

---

README.md
src/components/data/allcourses.json

I have added simplilearn beginner dsa course covering basics it has completion certificate also.Issue #456.

Added Beginner DSA course

---

README.md
src/components/data/allcourses.json

Add scientific computing with Python

---

README.md
src/components/data/allcourses.json

@avinash201199 please review it.
This issue is related to #472 and should be fixed by this PR.

added course machine learning with python

---

src/index.css

This pull request contains the updated code for '"All Courses" Section Design Enhancement'. The issue related to this PR is as follows:
"All Courses" Section Design Enhancement #471

"All Courses" Section Design Enhancement 

---

README.md
src/components/data/allcourses.json

Add A Free Networking course
Course Name - Network Support and Security
Organization - Cisco
Website - https://skillsforall.com/course/network-support-security?courseLang=en-US
After completing the course they will provide a free certificate.

Add A Free Networking course

---

README.md
src/components/data/allcourses.json

I have added the FastAPI course which was not present

Added FastAPI course

---

README.md
src/components/data/allcourses.json

This is a basics course provided by great learning academy for free to gain expereance on react. After finishing course they will provide a certificate that can be show in resume.

Add React Free Course

---

README.md
src/components/data/allcourses.json

This PR contains the source of added "Database Management System Course" : https://github.com/avinash201199/Free-courses-with-Certificates/issues/482
Close : https://github.com/avinash201199/Free-courses-with-Certificates/issues/482
**Additional Context**
Please @avinash201199 review my pull request and merge it under **Hacktoberfest** label ?

[Hacktoberfest'23] : Added Database Management System Course

---

README.md
src/components/data/allcourses.json

I have added the Ethereum Developer Bootcamp from Alchemy University to the project. It's free for everyone, and when you finish it, you get a certificate in the form of an NFT.

Add Ethereum Developer Bootcamp

---

src/index.css

This pull request contains the updated code for the misalignment of "Featured Courses" headings. The issue related to this PR is as follows:
Misalignment of "Featured Courses" Each Course Headings #479

Misalignment of "Featured Courses" Each Course Headings 

---

README.md
src/components/data/allcourses.json

Add Data Visualization course provided by freecodecamp.
It is a free course and they provide a free certificate that anyone can add to their resume.

Add free Data Visualization course

---

README.md
src/components/data/allcourses.json

**Fixes https://github.com/avinash201199/Free-courses-with-Certificates/issues/494** 
Please @avinash201199 review my pull request and merge it under the Hacktoberfest label. I have also created a markdown for this pull request.

[Hacktoberfest'23]: Computer networking course added

---

README.md
src/components/data/allcourses.json

I have added a new course Ethical Hacking and also added the description in the Readme.md file, please let me know if any changes are required, Thanks

Course added

---

src/index.css

This PR contains the updated code for the hover effect design enhancement of sidebar items. The related issue to this PR is as follows:
Sidebar Icon Hover Effect Design Enhancement #502

Sidebar Icon Hover Effect Design Enhancement 

---

README.md
src/components/data/allcourses.json

Added new course on AWS
Closes #513

Added New Course on AWS

---

README.md
src/components/data/allcourses.json

After completing all the exercises and the final project we get the CS50 certificate for free as shown in the link provided.

Add Harvard CS50 - Introduction to programming with python

---

README.md
src/components/data/allcourses.json

I have added 'Database and SQL' course link from Infosys Springboard which provides a certificate for completely free. 
The mode of teaching is English, So that everyone can watch their videos. Apart from that they also provide exercise hands-on for writing SQL queries and we need to pass the assessment test at last for the certificate. I personally like this course because it made me a good touch with SQL and Database concepts.
If this change is relevant then looking forward to getting it merged.
Thank you

added Database and SQL

---

README.md
src/components/data/allcourses.json

It is a free jenkins course with free certification.

Add jenkins free course

---

README.md
src/components/data/allcourses.json

hi @avinash201199    I have added free SQL certification course please merge it.

Update Readme .md

---

README.md
src/components/data/allcourses.json

Added Web-dev Course by Full stack open.

Added Full stack open Course

---

README.md
src/components/data/allcourses.json

I had added one more course of Hands-on Artificial Intelligence with TensorFlow, nowadays everything is based on Machine learning and Artificial Intelligence. By looking that I have one more course of Artificial Intelligence which has hands-on practice with Tensorflow which is one of the famous library for machine learning.

Added Hands-on Artificial Intelligence with TensorFlow

---

README.md
src/components/data/allcourses.json

I have added data science mathematics course for students to learn and grow in field of data science

Added data science mathematics course

---

src/components/allcourse.jsx
src/styles/allcourse.css

I created a back to top button with smooth scroll behaviour.
@avinash201199  Please review it and merge it within the main branch under HacktoberFest2023.

Added Back to top button

---

README.md
src/components/data/allcourses.json

add: Software Testing/Quality Assurance course info

---

package-lock.json
package.json
src/components/data/allcourses.json

This PR resolves issue #594, which was related to errors in the `allcourses.json` data and localhost not running correctly. The following changes have been made to address the issue:
- Fixed syntax errors in `allcourses.json`.
- Corrected data formatting and structure.
- Ensured that the JSON file is valid and can be properly parsed.
- Localhost running properly 
Testing:
- Verified that the corrected `allcourses.json` data now loads without errors.
- Confirmed that the website runs successfully on localhost without issues.
Screenshot:
@avinash201199 Please review and merge. Thanks!

Fix: Resolve error in allcourses.json and enable successful localhost run

---

package-lock.json
package.json
src/components/data/allcourses.json

Reverts avinash201199/Free-courses-with-Certificates#597

Revert "Fix: Resolve error in allcourses.json and enable successful localhost run"

---

README.md
src/components/data/allcourses.json

Reverts avinash201199/Free-courses-with-Certificates#577

Revert "add: Software Testing/Quality Assurance course info"

---

README.md
src/components/data/allcourses.json

Reverts avinash201199/Free-courses-with-Certificates#573

Revert "Update readme.md"

---

src/components/allcourse.jsx
src/styles/allcourse.css

Reverts avinash201199/Free-courses-with-Certificates#572

Revert "Added Back to top button"

---

README.md
src/components/data/allcourses.json

Reverts avinash201199/Free-courses-with-Certificates#570

Revert "Added data science mathematics course"

---

src/components/footer.jsx
src/styles/footer.css

Reverts avinash201199/Free-courses-with-Certificates#568

Revert "modified the footer"

---

README.md
src/components/data/allcourses.json

Added new course on Flutter
Closes #557

Added New Course on Flutter

---

README.md
src/components/data/allcourses.json

feat: add new frontend certification

---

README.md
src/components/data/allcourses.json

update allcourses.json and README.md

Add course: MySQL Basics by Great Learning

---

README.md
src/components/data/allcourses.json

Fixes #609
I have updated readme file as well as allcourses.json file in src file tree

Adds two courses in ethical hacking section

---

README.md
src/components/data/allcourses.json

Added a new free Artificial Intelligence course with certification by Simplilearn.

Add Free Artificial Intelligence Course with Certification

---

src/components/data/allcourses.json

Add python tkinter course

---

README.md
src/components/data/allcourses.json

I have added free Internet of Things Course with certification. 
Simplilearn - Introduction to IoT (https://www.simplilearn.com/learn-iot-basics-skillup)

Add free Internet of Things Course with certification

---

README.md
src/components/data/allcourses.json

I have added free MySQL course with certification.
Scaler - SQL for Beginners (https://www.scaler.com/topics/course/sql-using-mysql-course/)

Add free MySQL course with certification

---

README.md

I have addressed the issue #654 . Here I created a new section and added a certification course to it.

Update README Added Prompt Engineering Course

---

README.md
src/components/data/allcourses.json

I have added the **free certification Flask course** which was not present
@avinash201199 Thank you for assigning me 🙂

Added Flask course and updated README

---

README.md
src/components/data/allcourses.json

I have added the **free certification Graphic design** courses under UI/UX
@avinash201199 Thank you for assigning me

Added new Graphic design courses and updated README

---

README.md
src/components/data/allcourses.json

Add database normalization free course with certificate.
@avinash201199 please review and merge this PR for issue #686

[ADDED] Database Normalization free course with certificate from Great learning academy

---

src/index.css

This pull request contains the updated code for the addition of hover effect on navbar options. The issue related to this pull request is as follows:
Addition of Hover Effect Design on Navbar Options #668

Addition of Hover Effect Design on Navbar Options 

---

README.md
src/components/data/allcourses.json

please Check my contribution. Thanks.

Add Free SQL Course with certificate in  README.md

---

README.md
src/components/data/allcourses.json

Added Code Red's cybersecurity course

---

README.md
src/components/data/allcourses.json

Adds an additional free course for Javascript from Scaler.
Updates Readme.md

Adds Scaler - Javascript Certification Course

---

README.md
src/components/data/allcourses.json

Closes #680 
Please accept this PR with appropriate label.

Adding Deep Learning courses

---

src/components/navbar.jsx
src/styles/navbar.css

I have sorted the issue of outcoming of the search bar component.
can you plz label this issue as hacktoberfest

Task of making the the thing responsice is done.

---

src/components/data/allcourses.json

fixes #719 
Please check this out I have solved the issue of empty card.
Before:
After:
Thankyou @avinash201199

FIXED: fixed issue in databases and sql card

---

README.md
src/components/data/allcourses.json

Closes: #726 
- This PR adds resources and links to certification of graphQL

Add GraphQL certification resources

---

src/components/data/allcourses.json

Fixes #716 
1. Combined 2 groups
2. Fixed the icon of SQL course
3. Removed a course that wasn't pointing to a course

Fixed some UI issues

---

README.md

Closes #731 
Please merge this pull request @avinash201199

added license section

---

README.md
src/components/data/allcourses.json

Closes #730 
@avinash201199  . Please merge this PR

Added new TypeScript Course

---

src/components/data/allcourses.json

Added one of the emerging course i.e Prompt Engineering with Free certification.

added  prompt engineering

---

src/components/data/allcourses.json

**Added a couple of certifications in go , graphql , cloud , AI.**

added new certifications

---

README.md
src/components/data/allcourses.json

I have created generative ai field and added two free courses in it.

Adding Generative AI courses #746

---

src/components/data/allcourses.json

feat: #753
- add new reactjs free course at react course section
- Comprehensive coverage of fundamental React concepts and best practices.
- Free access, making it accessible to a wider audience of learners.
- Includes certification upon completion, which is valuable for validating skills.
- Suitable for beginners and intermediate learners to strengthen their React.js knowledge.

feat(react-course): add new react course at react course section

---

src/components/data/allcourses.json

adding a free machine learning course to the list.

Adding a machine learning course

---

CONTRIBUTING.md
README.md
src/components/AboutPage.jsx
src/components/Dashboard.jsx
src/components/Layout.jsx
src/components/allcourse.jsx
src/components/data/allcourses.json
src/components/featured.jsx
src/components/footer.jsx

Hey , this PR closes #756 issue , I modified and improved the about page, modified nav bar in necessary pages, and made the pages more simple with minor changes that improves user interactivity and ease of use. @avinash201199 can you please take a look at it and merge this asap. Let me know if any changes are required :)

Modified About Page, Nav Bar and side bar according to the pages

---

README.md
src/components/data/allcourses.json

Hi @avinash201199 ,
I would like to contribute to this issue as part of Hacktoberfest. I Hope you will merge and Label it Hacktoberfest accepted.
Thank you!

Added SQL certification ( Hacktoberfest 2025 )

---

README.md
src/components/data/allcourses.json

Issue #774 
Added Artificial Intelligence free Certification Course from IBM skillsbuild

Added AI Fundamentals Course

---

README.md
src/components/data/allcourses.json

Added **JavaScript Data Structures and Algorithms** course by **freeCodeCamp** to the **JavaScript section** and updated the `README.md` accordingly.
[freeCodeCamp JavaScript DSA Course](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)
This closes #776

Add JavaScript Algorithms and Data Structures

---

src/components/data/allcourses.json

Added "Crafting Ethereum Blockchain using Solidity Course by Alison" to blockchain courses in `allCourses.json`.  This closes #780

Add: Ethereum Blockchain course by Alison

---

src/components/data/allcourses.json

i have added the correct aws icon to the ui as specified .
This pr fixes the  isssue  #795 .
@avinash201199 Can u please check this pr out ? Also can u please assign the labels accordingly?

added proper icons
